src/Ploi/Http/Response.php, src/Ploi/Ploi.php, src/Ploi/Resources/Resource.php, src/Ploi/Resources/Server/Server.php, src/Ploi/Resources/Server/Site.php, src/Ploi/Traits/HasHistory.php
Discovered by @phpstan
@Cannonb4ll
=> Fix types all around

src/Ploi/Ploi.php, src/Ploi/Resources/Database.php, src/Ploi/Resources/Resource.php
Tried to keep this close to existing code but did add in an "action" variable to be able to build the endpoint similar to how id is injected.
=> Added Database Acknowledge and Forget functions.

src/Ploi/Resources/Database.php, src/Ploi/Resources/DatabaseBackup.php, src/Ploi/Resources/Resource.php, src/Ploi/Resources/Server.php
Okay lets try this again! Created DatabaseBackup resource and moved get and create backup functions to there. 
$ploi->server(123)->databases(123)->backups()->get();
$ploi->server(123)->databases(123)->backups(123)->get();
$ploi->server(123)->databases(123)->backups()->create(0,'local',null,null,'/home/ploi/backup');
=> Dev database backup

src/Ploi/Ploi.php
This just adds an alias function to `server`, as it sounds more fluent to me since often times you'll be dealing with multiple "servers".
```php
$ploi->servers()->get();
```
=> Add server function alias

src/Ploi/Resources/Resource.php, src/Ploi/Resources/Server.php, tests/Ploi/Resources/ServerTest.php
This adds functions for creating a custom server and a function to start the installation process once the key has been added. There's also a function to get ssh keys for a server.
=> Add functions for creating custom server and retrieving ssh keys

src/Ploi/Resources/Server.php, tests/Ploi/Resources/ServerTest.php
There was a bug with building the url without an id. Added more tests.
=> Fix endpoint building bug

src/Ploi/Resources/Environment.php, src/Ploi/Resources/Site.php
Adds support for getting and updating a site's environment file
=> Add environment support

README.md
Updates README with recent changes to some methods
=> Updates parameters in examples for README

README.md, src/Ploi/Resources/Server.php, tests/Ploi/Resources/ServerTest.php
Added test and examples to documentation also.
=> Add server restart and server monitor endpoints

src/Ploi/Resources/Server.php
The response isn't nested inside of `data`
=> Set id from json, not data

.travis.yml
test against php 7.3, 7.4 and 8.0
=> update travis tests config

README.md, src/Ploi/Resources/Certificate.php, src/Ploi/Resources/Cronjob.php, src/Ploi/Resources/Daemon.php, src/Ploi/Resources/Database.php, src/Ploi/Resources/DatabaseBackup.php, src/Ploi/Resources/NetworkRule.php, src/Ploi/Resources/Queue.php, src/Ploi/Resources/Redirect.php, src/Ploi/Resources/Script.php, src/Ploi/Resources/Server.php, src/Ploi/Resources/Site.php, src/Ploi/Resources/SystemUser.php, src/Ploi/Traits/HasPagination.php, tests/Ploi/Resources/ServerTest.php, tests/Ploi/Resources/SiteTest.php
Created HasPagination trait and added it to applicable resources. Also added usage to readme examples.
=> Adds pagination methods to applicable resources

README.md, src/Ploi/Resources/FastCgi.php, src/Ploi/Resources/Site.php
Also fixed an error in readme for aliases
=> Adds FastCGI cache resource

README.md, src/Ploi/Ploi.php, src/Ploi/Resources/Incident.php, src/Ploi/Resources/StatusPage.php
I noticed the API for incidents doesn't allow you get get a specific one by ID, the code currently allows it (just returns null) in case this is intended to be added.
Let me know if I need to change this 👍
=> Adds Status Page and Status Page Incidents resources

README.md, src/Ploi/Resources/Site.php, src/Ploi/Resources/Tenant.php
https://developers.ploi.io/tenants/
=> Add tenants resource

README.md, src/Ploi/Resources/Site.php
=> Add update method to site resource

README.md, src/Ploi/Resources/Repository.php
=> Add toggle quick deploy method to repository resource

README.md, src/Ploi/Resources/Database.php
=> Add duplicate method to database resource

README.md, src/Ploi/Resources/Database.php, src/Ploi/Resources/DatabaseUser.php
=> Add database users resource

README.md, src/Ploi/Ploi.php, src/Ploi/Resources/WebserverTemplate.php
=> Add webserver template resource

README.md, src/Ploi/Resources/LoadBalancer.php, src/Ploi/Resources/Server.php
=> Add load balancer resource

README.md, src/Ploi/Resources/Monitors.php, src/Ploi/Resources/Site.php
=> Adds monitoring resource

README.md, src/Ploi/Resources/NginxConfiguration.php, src/Ploi/Resources/Site.php
=> Add nginx configuration resource

README.md, src/Ploi/Resources/Site.php
=> Adds laravel horizon statistics method

.github/workflows/php_test.yml
Not exactly what I wanted but the current tests are way to random 😅 
-Doesn't properly clean up the created site
- Doesn't seem te resume a suspended site
Which causes tests to fail
Currently don't have any more time (and knowledge) to dig into this, at least there is this Github action prepared now that builds the project. Enabling testing for this this should be easy.
=> Added github action for tests

src/Ploi/Resources/Certificate.php
Added the option to force the request, bypassing the validation from Ploi
=> Added force option to certificate

src/Ploi/Resources/Certificate.php
From this commit 6d7ee404f8bfe4914cfa30f485283817db9540c1
=> Fix parameter type in Certificate
